# MSA 8600

Please learn to work with `numpy` and `pandas`.

- Scalar: a number.
- Vector: a number with direction
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers (0-dim: scalar, 1-dim: vector, 2-dim: matrix)

Note: We can not change constants. But we can change variables.

In [1]:
import tensorflow as tf

tf.__version__

2023-03-17 11:03:53.823974: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


'2.11.0'

### Rank 0 tensor

In [3]:
s = tf.constant(12)
print(s)

tf.Tensor(12, shape=(), dtype=int32)


2023-03-17 11:04:27.943182: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
s.ndim

0

### Vectors

In [5]:
v = tf.constant([20,12])
print(v)
print("Dimension:", v.ndim)

tf.Tensor([20 12], shape=(2,), dtype=int32)
Dimension: 1


### Matrix

In [6]:
m = tf.constant([[4,5],
                [-2,6]])
print(m)

tf.Tensor(
[[ 4  5]
 [-2  6]], shape=(2, 2), dtype=int32)


In [7]:
m2 = tf.constant([[4.2,5.3],
                [-2,6]], dtype=tf.float16)
print(m2)

tf.Tensor(
[[ 4.2  5.3]
 [-2.   6. ]], shape=(2, 2), dtype=float16)


In [8]:
print(m2.ndim)

2


In [9]:
t1 = tf.constant([4, 3])
t2 = tf.Variable([4, 3])

#t1[0].assign(2) raises an error

t2[0].assign(2)

print(t2)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>
