# MSA 8600

Please learn to work with `numpy` and `pandas`.

- Scalar: a number.
- Vector: a number with direction
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers (0-dim: scalar, 1-dim: vector, 2-dim: matrix)

Note: We can not change constants. But we can change variables.

In [ ]:
import tensorflow as tf

tf.__version__

'2.11.0'

### Rank 0 tensor

In [ ]:
s = tf.constant(12)
print(s)

tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
s.ndim

0

### Vectors

In [ ]:
v = tf.constant([20,12])
print(v)
print("Dimension:", v.ndim)

tf.Tensor([20 12], shape=(2,), dtype=int32)
Dimension: 1


### Matrix

In [ ]:
m = tf.constant([[4,5],
                [-2,6]])
print(m)

tf.Tensor(
[[ 4  5]
 [-2  6]], shape=(2, 2), dtype=int32)


In [ ]:
m2 = tf.constant([[4.2,5.3],
                [-2,6]], dtype=tf.float16)
print(m2)

tf.Tensor(
[[ 4.2  5.3]
 [-2.   6. ]], shape=(2, 2), dtype=float16)


In [ ]:
print(m2.ndim)

2


In [ ]:
t1 = tf.constant([4, 3])
t2 = tf.Variable([4, 3])

#t1[0].assign(2) raises an error

t2[0].assign(2)

print(t2)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>
