# MSA 8600

Please learn to work with `numpy` and `pandas`.

- Scalar: a number.
- Vector: a number with direction
- Matrix: a 2-dimensional array of numbers
- Tensor: an n-dimensional array of numbers (0-dim: scalar, 1-dim: vector, 2-dim: matrix)

Note: We can not change constants. But we can change variables.

In [1]:
import tensorflow as tf

tf.__version__

2023-03-17 11:03:53.823974: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


'2.11.0'

### Rank 0 tensor

In [3]:
s = tf.constant(12)
print(s)

tf.Tensor(12, shape=(), dtype=int32)


2023-03-17 11:04:27.943182: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
s.ndim

0

### Vectors

In [5]:
v = tf.constant([20,12])
print(v)
print("Dimension:", v.ndim)

tf.Tensor([20 12], shape=(2,), dtype=int32)
Dimension: 1


### Matrix

In [6]:
m = tf.constant([[4,5],
                [-2,6]])
print(m)

tf.Tensor(
[[ 4  5]
 [-2  6]], shape=(2, 2), dtype=int32)


In [7]:
m2 = tf.constant([[4.2,5.3],
                [-2,6]], dtype=tf.float16)
print(m2)

tf.Tensor(
[[ 4.2  5.3]
 [-2.   6. ]], shape=(2, 2), dtype=float16)


In [8]:
print(m2.ndim)

2


In [9]:
t1 = tf.constant([4, 3])
t2 = tf.Variable([4, 3])

#t1[0].assign(2) raises an error

t2[0].assign(2)

print(t2)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>


In [1]:
import numpy as np
def initialize_parameters(layer_dims):
    parameters = {}
    L = len(layer_dims) - 1 # number of layers in the network
    for l in range(1, L + 1):
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1]) * 0.01
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
    return parameters



In [6]:
parameters = initialize_parameters([2, 4, 4, 1]) #2 neurons, 4 layers, 4 neurons per layer, 1 input
print(parameters["W1"])
print(parameters["b1"])


[[ 0.00513891 -0.00641006]
 [-0.00389762  0.01762219]
 [ 0.00890082  0.01369906]
 [-0.01568453  0.01111635]]
[[0.]
 [0.]
 [0.]
 [0.]]


In [7]:
def cross_entropy_loss(y_pred, y_true): #y_true the actual label, y_pred the predicted label
    batch_size = y_pred.shape[0] #batch size is the number of samples in the batch
    eps = 1e-12  #epsilon for numerical stability (eps)
    loss = -1 / batch_size * np.sum(y_true * np.log(y_pred)) #logloss equation
    return loss

In [10]:
y_pred = np.array([[0.3, 0.7, 0.1],
                  [0.6, 0.4, 0.9],
                  [0.8, 0.2, 0.2]])

y_true = np.array([1, 0, 1])

loss = cross_entropy_loss(y_pred, y_true)
print(loss)

None


In [ ]:
import tensorflow as tf

In [12]:
$ brew install git

SyntaxError: invalid syntax (2627020378.py, line 1)